---
title: "Untitled"
author: "Donald Moratz"
date: "2024-03-12"
output: html_document
---

```{r, include=FALSE}
#Clear R environment
rm(list = ls())

#Set seed for random number generation as well as R version (which changed between version 3.4.2 and 3.6.0)
set.seed(3184)

knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
#Load the required packages
library(ggplot2)
library(stringdist)
library(stringr)
library(knitr)
library(lubridate)
library(tidyr)
library(plotly)
library(glmnet)
library(caret)
library(scales)
library(openxlsx)
library(kableExtra)
library(pBrackets)
library(zoo)
library(ggpubr)
library(tinytex)
library(Rmisc)
library(purrr)
library(here)
library(readr)
library(data.table)
library(dplyr)
library(stargazer)
library(pander)
library(estimatr)
library(tseries)
library(plm)
library(lmtest)
library(cowplot)
options(knitr.table.format = "latex")
options(scipen = 999)
```

```{r, include=FALSE, echo = FALSE}
#Load Permanent versions of the data
wd = here::here()

path_dropbox <- function(...) {
  # default guess
  base <- "~/Dropbox/ML for Peace/"

  # user/computer-specific alternatives
  if (Sys.info()["user"]=="andybega") {
    base <- "~/Dropbox/Work/ML for Peace/"
  }
  # jeremy: office windows
  if (Sys.info()["user"]=="jerem") {
    base <- "C:/Users/jerem/Dropbox/ML for Peace/"
  }
  # jeremy: home linux
  if (Sys.info()["user"]=="jerem") {
    base <- "/home/jeremy/Dropbox/ML for Peace/"
  }
  # donald
  if(Sys.info()["user"] == "skybl") {
    base <- "D:/Dropbox/ML for Peace/"
  }
  # Check to make sure the directory exists and is correct
  if (!dir.exists(base)) {
    stop("Go edit path_dropbox in the code chunk and add your path to the Dropbox folder")
  }

  file.path(base, ...)
}

dropbox <- path_dropbox()

```


```{r, include=FALSE, echo = FALSE}
# Set List of Countries
countries <- c("Albania","Azerbaijan","Armenia","Belarus","Georgia","Hungary",
               "Kazakhstan","Kosovo","Kyrgystan","Moldova","Serbia","Turkey","Ukraine","Roya project") 


new_date <- "2024_3_12"

# New Reader Function
df_list <- list()
for(i in countries){
  sources <- dir(paste0(dropbox,"/Donald_RAI/",i,"/",new_date,"/"), pattern = "*.csv", full.names = TRUE)
  temp_df_list <- map(sources, read_csv)
  df_list <- c(df_list, temp_df_list)
}

# Read in Country Counts
# Read civic related counts
articles <- NULL
for(i in countries){
  sources <- list.files(path=paste0(dropbox,"/Donald_RAI/",i,"/",new_date,"/"))
  for(j in sources){
    a <- tryCatch(read.csv(paste0(dropbox,"/Donald_RAI/",i,"/",new_date,"/",j)),error=function(err) as.data.frame(matrix(data = 0,nrow=1,ncol=35))) %>%
      select(-any_of(c("mordecai_locations","localpath","event_type_civic1","civic1")))
    a$country <- i
    articles<- tryCatch(rbind(articles,a), error=function(err) articles)
  }
}

unique_source_domains <- unique(unlist(map(df_list, ~unique(.$source_domain))))
old_unique_domains <-unique(articles$source_domain)
setdiff(unique_source_domains,old_unique_domains)

#write.csv(articles,file="total_combined_articles.csv")

articles_new <- NULL
for(i in countries){
  sources <- list.files(path=paste0(dropbox,"/Donald_RAI/",i,"/",new_date,"/"))
  for(j in sources){
    a <- tryCatch(read.csv(paste0(dropbox,"/Donald_RAI/",i,"/",new_date,"/",j)),error=function(err) as.data.frame(matrix(data = 0,nrow=1,ncol=5)))
    if(nrow(a)==1){
      a <- a
      } else{
        a <- a %>%
          select(c("X_id","date_publish","source_domain","maintext_translated","title_translated"))
        
        a$country <- i
        
        articles_new<- tryCatch(rbind(articles_new,a), error=function(err) articles_new)
        }
    #select(c("X_id","date_publish","maintext_translated","title_translated"))
  }
}

new_article_domains <- unique(articles_new$source_domain)

setdiff(unique_source_domains,new_article_domains)

setdiff(unique_source_domains,old_unique_domains)

# Filter out articles that the old process caught and were therefore already coded
articles_new <- articles_new %>%
  filter(!source_domain %in% old_unique_domains)


# Relabel Roya Sources with their country names
articles_new$country[articles_new$source_domain == "1lurer.am"] <- "Armenia"
articles_new$country[articles_new$source_domain == "agenda.ge"] <- "Georgia"
articles_new$country[articles_new$source_domain == "azerbaijan-news.az"] <- "Azerbaijan"
articles_new$country[articles_new$source_domain == "azertag.az"] <- "Azerbaijan"
articles_new$country[articles_new$source_domain == "en.armradio.am"] <- "Armenia"
articles_new$country[articles_new$source_domain == "eng.belta.by"] <- "Belarus"
articles_new$country[articles_new$source_domain == "kazpravda.kz"] <- "Kazakhstan"
articles_new$country[articles_new$source_domain == "ktrk.kg"] <- "Kyrgyzstan"
articles_new$country[articles_new$source_domain == "lajme.rtsh.al"] <- "Albania"
articles_new$country[articles_new$source_domain == "magyarnemzet.hu"] <- "Hungary"
articles_new$country[articles_new$source_domain == "moldova-suverana.md"] <- "Moldova"
articles_new$country[articles_new$source_domain == "qazaqstan.tv"] <- "Kazakhstan"
articles_new$country[articles_new$source_domain == "rtklive.com"] <- "Kosovo"
articles_new$country[articles_new$source_domain == "rts.rs"] <- "Serbia"
articles_new$country[articles_new$source_domain == "top-channel.tv"] <- "Albania"
articles_new$country[articles_new$source_domain == "trthaber.com"] <- "Turkey"
articles_new$country[articles_new$source_domain == "ukrinform.net"] <- "Ukraine"
articles_new$country[articles_new$source_domain == "uza.uz"] <- "Ukraine"

write.csv(articles_new,file="additional_total_combined_articles.csv")

#article_sample <- articles[sample(nrow(articles),100,replace=FALSE),]

#write.csv(article_sample,file="combined_articles.csv")
```